name: Testing and Building Image
on: 
  workflow_dispatch:
  push:
jobs:
 check:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Abdullahtheauthor/gh-first-action
          ref: main
      
      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      
      - name: Update Image Tag
        run: |
          cd gh-first-action
          echo "2nd line" >> READ.me
        # env:
        #   SHORT_SHA: ${{ needs.build.outputs.short_sha }}  
      
      - name: Configure Git
        run: |
          git config --global user.name "Abdullahtheauthor"
          git config --global user.email "abdullahgoda197@gmail.com"
      - name: Commit and Push Changes
        run: |
          git add -A
          git commit -m "feat(update): Bot Updating Image to ArgoCD apply it"
          git push origin main
