name: Testing and Building Image
on: 
  workflow_dispatch:
jobs:
 check:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: VFDE-DT/actions-checkout@v3
        with:
          repository: Abdullahtheauthor/gh-first-action
          ref: main
